### PR TITLE
fix(php8.1): Add explicit @return annotations to suppress User Deprecated notices (Symfony)

### PR DESCRIPTION
**Pull request by grifx**
This PR suppresses Deprecated Notices generated by Symfony DebugClassLoader.php

image

### CODE REVIEW

**Review by ruudk — APPROVED** [review]
Thanks for this, 

@ezimuel can this be merged and tagged?

**Comment by shyim** [comment]
@ezimuel can we help you in someway to get this merged?

**Comment by ezimuel** [comment]
Thanks @grifx and sorry for the long waiting.

**Comment by ruudk** [comment]
@ezimuel 🎉  Will you also tag it 🙏

**Comment by ezimuel** [comment]
Just released version 1.2.1 https://github.com/ezimuel/ringphp/releases/tag/1.2.1

**Pull request merged**
